//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RamXML
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ramxmlEntities : DbContext
    {
        public ramxmlEntities()
            : base("name=ramxmlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dropdown> dropdown { get; set; }
        public virtual DbSet<ontology> ontology { get; set; }
        public virtual DbSet<concepts> concepts { get; set; }
        public virtual DbSet<doc> doc { get; set; }
        public virtual DbSet<nodes> nodes { get; set; }
    }
}
