//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RamXML
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc
    {
        public doc()
        {
            this.concepts = new HashSet<concepts>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<concepts> concepts { get; set; }
    }
}
