//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RamXML
{
    using System;
    using System.Collections.Generic;
    
    public partial class nodes
    {
        public int id { get; set; }
        public int id_concept { get; set; }
        public string nodeName { get; set; }
        public string value { get; set; }
    
        public virtual concepts concepts { get; set; }
    }
}
