//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RamXML
{
    using System;
    using System.Collections.Generic;
    
    public partial class ontology
    {
        public int id { get; set; }
        public int id_concept { get; set; }
        public string dropdown1 { get; set; }
        public string dropdown2 { get; set; }
        public string dropdown3 { get; set; }
        public int id_doc { get; set; }
    }
}
